name: Setup Capacitor for Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-capacitor-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies (ignore peer deps conflicts)
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build web assets for Capacitor
      - name: Build web assets
        run: npm run build

      # 5. Install Capacitor core + CLI
      - name: Install Capacitor
        run: |
          npm install @capacitor/core --legacy-peer-deps
          npm install -D @capacitor/cli --legacy-peer-deps

      # 6. Initialize Capacitor (only if config doesn’t exist)
      - name: Initialize Capacitor
        run: |
          if [ ! -f capacitor.config.json ]; then
            npx cap init "Perfect Piano" "com.pianoman.sing" --web-dir=dist
          fi

      # 7. Install Capacitor Android platform
      - name: Add Capacitor Android
        run: |
          npm install @capacitor/android --legacy-peer-deps
          npx cap add android

      # 8. Sync project
      - name: Sync Capacitor Android
        run: npx cap sync android

      # 9. (Optional) Open Android Studio
      # - name: Open Android Studio
      #   run: npx cap open android
