      # 3. Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build web assets
      - name: Build web assets
        run: npm run build

      # 5. Install Capacitor core + CLI
      - name: Install Capacitor
        run: |
          npm install @capacitor/core --legacy-peer-deps
          npm install -D @capacitor/cli --legacy-peer-deps

      # 6. Initialize Capacitor (only if config doesn’t exist)
      - name: Initialize Capacitor
        run: |
          if [ ! -f capacitor.config.json ]; then
            npx cap init "Perfect Piano" "com.pianoman.sing" --web-dir=dist
          fi

      # 7. Add Capacitor Android
      - name: Add Capacitor Android
        run: |
          npm install @capacitor/android --legacy-peer-deps
          npx cap add android

      # 8. Sync project
      - name: Sync Capacitor Android
        run: npx cap sync android
